### ISSUE TITLE
Add tests for Windows

### ISSUE THREAD

**Issue by ai** [mbalabash/estimo#13]
I worry that `findChrome.js` will not work on Windows.

We can use Travis CI, it support Window machines. But we need to add tests for the case when we have Chrome on the machine.

**Comment by mbalabash** [comment]
Ok
I will add test for this case on these weekends.

**Comment by mbalabash** [comment]
@ai 
I added tests for `findChrome` and Windows environment on TravisCI.
Seems like `findChrome` works on Windows. 

Last step is need to fix strange behaviour with TravisCI. 
I got: `Done. Your build exited with 0.` 

But then: `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`

[Travis Build History](https://travis-ci.org/mbalabash/estimo/jobs/566079386)

I will post updates here.

**Comment by mbalabash** [comment]
Known similar problem on Travis - https://travis-ci.community/t/build-terminated-after-build-exited-successfully/4426

**Comment by mbalabash** [comment]
Also i got issue with launching chrome on Windows.
But [this fix](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-windows) solves problem.

**Comment by mbalabash** [comment]
Done.
I added tests for `findChrome` and Windows test environment.

https://travis-ci.org/mbalabash/estimo/builds/566316304
https://travis-ci.org/mbalabash/estimo/builds/566324361

**Comment by ai** [comment]
Perfect
