### ISSUE TITLE
Add Chanelog

### ISSUE THREAD

**Issue by ai** [mbalabash/estimo#18]
There are a lot of reasons to keep Change Log https://keepachangelog.com/en/1.0.0/

For instance, I do not know is it safe to update to 2.0 (and it is hard to find it from git history). I have changelog in all my open source projects.

**Comment by mbalabash** [comment]
Hi @ai 
Yes, it's a good idea.

I added [CHANGELOG.md](https://github.com/mbalabash/estimo/blob/master/CHANGELOG.md).

If it still not friendly / clear, please let me know.
Thanks
