### ISSUE TITLE
Feature request: compare two (or more?) files

### ISSUE THREAD

**Issue by jakub-g** [mbalabash/estimo#24]
Getting absolute values is the current use case, but being able to compare two or more scripts as a built-in could be interesting.

Imagine I take an existing script and do some optimizations. I want to know how much improvement I can expect.

# Before

`estimo -r before.js`
`estimo -r after.js`

_manual comparison of output_

programmatic API:

`await estimo('before.js', settings)`
`await estimo('after.js', settings)`

# After

`estimo -r before.js -r after.js`

programmatic API:

`await estimo(['before.js', 'after.js'], settings)`

To be decided how the output should look like in case of > 1 file, but ideally it should have both absolute numbers, and diff (absolute and in %) compared to the baseline (baseline being the first file).

**Comment by mbalabash** [comment]
Hey @jakub-g 
I like your idea. We can use metrics of the first file as a baseline. And then, compare other files metrics with this baseline.

Speaking about output, I like how [size-limit-action](https://github.com/andresz1/size-limit-action) shows diff. It includes the filename, absolute number, and deviation from baseline.

**Comment by mbalabash** [comment]
@jakub-g I'm going to start working on this issue next week.

**Comment by mbalabash** [comment]
Released in [`estimo@2.2.0`](https://github.com/mbalabash/estimo/blob/master/CHANGELOG.md#220)
