### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by ai** [mbalabash/estimo#3]
With [Travis CI](https://docs.travis-ci.com/user/tutorial/) all your commits will be tested in CI. Every pull request will be tested.

Also, we will be sure, that it works with GUI-less environment. 

1. Add `.travis.yml` to your project
2. Signup in Travis CI
3. Add a project in Travis CI website

```
language: node_js
cache: yarn
node_js:
  - node
  - "10"
  - "8"
```

**Comment by mbalabash** [comment]
Done
