### ISSUE TITLE
findChrome fails on win10 with chrome 93.0

### ISSUE THREAD

**Issue by BePo65** [mbalabash/estimo#31]
findChrome (e.g. called on `npm i`) just starts chrome and throws error when closing chrome.

Tracking things down I found out that the script identified correctly the installation path for chrome on my system ('"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"'), but that the command `.../chrome --version` is no longer supported (see also [entry on stackoverflow](https://stackoverflow.com/questions/50880917/how-to-get-chrome-version-using-command-prompt-in-windows)).

My system:
windows 10 pro 21H1
Chrome 93.0

**Comment by mbalabash** [comment]
Hey! @BePo65
Sorry for long response time. I was a bit busy with my personal stuff.

Would you like to make a PR with fix for this issue?

**Comment by mbalabash** [comment]
@BePo65 Do you still have that problem or it was a one-time situation?

**Comment by BePo65** [comment]
I was off for 2 weeks, so I could not answer in time.
Yes I will prepare a PR for this.
