### ISSUE TITLE
Consider using Tracium instead of Big Rig

### ISSUE THREAD

**Issue by aslushnikov** [mbalabash/estimo#4]
Hi folks!

[Big Rig](https://github.com/googlearchive/node-big-rig) hasn't been updated for a long time. Over the last years, Chrome Traces format has changed quite a bit, so there's **no guarantee** Big Rig results are sensible/trustworthy (most likely they're not).

[Google Lighthouse](https://github.com/GoogleChrome/lighthouse) is one of the projects that parses Chrome Traces correctly. Since there are a few use cases around that rely on Chrome Traces (including "estimo"), we extracted trace-parsing logic from Lighthouse into a standalone library - [Tracium](https://github.com/aslushnikov/tracium).

Consider using Tracium for a much more trustworthy results.

Thanks!

**Comment by mbalabash** [comment]
Hi @aslushnikov 

> we extracted trace-parsing logic from Lighthouse into a standalone library - Tracium.

It's a great news! Thanks for sharing it.
I will test [Tracium](https://github.com/aslushnikov/tracium) and prepare to migrate on this lib in few days.

And thanks for your attention to this project 😊.

**Comment by aslushnikov** [comment]
@mbalabash also, many of the metrics you care about - such as script duration, layout duration and so on, are available with Puppeteer's [`page.metrics()`](https://pptr.dev/#?product=Puppeteer&version=v1.14.0&show=api-pagemetrics) api - so you might not need to do trace processing altogether.

Consider the following example:

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://google.com');
  console.log(await page.metrics());
  await browser.close();
})();
```

Yields: 
```
{ Timestamp: 2794.932485,
  Documents: 4,
  Frames: 1,
  JSEventListeners: 126,
  Nodes: 333,
  LayoutCount: 8,
  RecalcStyleCount: 20,
  LayoutDuration: 0.033013,
  RecalcStyleDuration: 0.008684,
  ScriptDuration: 0.168618,
  TaskDuration: 0.332174,
  JSHeapUsedSize: 10366872,
  JSHeapTotalSize: 14053376 }
```

**Comment by mbalabash** [comment]
Wow! It's a good new API.

I can add new mode to estimo which will use only puppeteer.
In some cases (including [Size Limit](https://github.com/ai/size-limit)) it will be enough and should work faster.

Does `ScriptDuration` includes time for all events related to Javascript?
Is it possible to see all handled events for each metric?

Thanks!

**Comment by aslushnikov** [comment]
> Does ScriptDuration includes time for all events related to Javascript?
Is it possible to see all handled browser events for some metric?

@mbalabash the `page.metrics` doesn't rely on chrome traces - instead it is powered by DevTools protocol, using [`Performance.getMetrics`](https://vanilla.aslushnikov.com/?Performance.getMetrics) call.

This DevTools protocol method does a pretty good job on instrumenting script execution in Chromium.
If you're into reading chromium code, here's the [relevant place](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/inspector/inspector_performance_agent.cc?sq=package:chromium&g=0&l=125).

**Comment by mbalabash** [comment]
OK. 
I will try to figure this out for a better understanding of how it works.
Thanks for information 👍

**Comment by ai** [comment]
Wow, it is a very interesting idea. Ping me if you need any help.

**Comment by mbalabash** [comment]
I prepared new version with [Tracium](https://github.com/aslushnikov/tracium) and [Puppeteer](https://pptr.dev/). 
Now i want to test performance and stability.

I will ping you @ai when it will be ready to release. Also i can help with upgrade it in [Size Limit](https://github.com/ai/size-limit).

**Comment by mbalabash** [comment]
V2 uses [Tracium](https://github.com/aslushnikov/tracium) for parsing.
