### ISSUE TITLE
Add required ESM fields to `package.json`

### ISSUE THREAD

**Issue by ai** [mbalabash/estimo#44]
The current warning:

> DeprecationWarning: No "main" or "exports" field defined in the package.json for /home/ai/Dev/size-limit/node_modules/.pnpm/estimo@3.0.0/node_modules/find-chrome-bin/ resolving the main entry point "index.js", imported from /home/ai/Dev/size-limit/node_modules/.pnpm/estimo@3.0.0/node_modules/estimo/src/utils.js.

**Comment by mbalabash** [comment]
Should be fixed in `estimo@3.0.1`
