### ISSUE TITLE
Add --no-sandbox for Puppeter

### ISSUE THREAD

**Issue by ai** [mbalabash/estimo#8]
It will make Puppeter work on CI

https://github.com/ai/size-limit/issues/113

**Comment by igorkamyshev** [comment]
It not for any CI, I guess. But definitely for GitHub Actions.

**Comment by aslushnikov** [comment]
For many CI's there's a way to enable sandboxing appropriately: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox

We didn't look into Github Actions yet.

**Comment by igorkamyshev** [comment]
Yep, sure. I suggest add this option to your package. I tried to run a size-limit in GitHub Actions and need this parameter.

**Comment by igorkamyshev** [comment]
@mbalabash hey, friendly ping =)

I want use Size Limit in GitHub Actions and I really need this option. If you agree with this proposal, I can make a PR with this changes.

**Comment by mbalabash** [comment]
Hello
I'm was in vacation, sorry for slow response 🙃
Tomorrow i will add this option and test it asap.

**Comment by mbalabash** [comment]
@igorkamyshev I'm added this option. 

> It not for any CI, I guess. But definitely for GitHub Actions.

You are right. Travis CI still fails. 

Tracium throws `Fatal trace logic error - child cannot end after parent` only in docker environment.
Bad part is, this behavior unstable for same docker container and tests.

@aslushnikov Do you have any ideas?

**Comment by aslushnikov** [comment]
@mbalabash do you have a trace that throws this error?

**Comment by mbalabash** [comment]
@aslushnikov 
Sure. https://pastebin.com/raw/yFXr7kqk

**Comment by mbalabash** [comment]
@igorkamyshev released in v1.0.0
